apiVersion: v1
kind: Service
metadata:
  name: cost-db
spec:
  type: NodePort
  selector:
    app: cost-db
    env: stepzen-playground
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432