apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: stepzen-playground
  namespace: default
spec:
  params:
    - name: url
      type: string
    - name: userHome
      type: string
    - name: imageRegistry
      type: string
      default: "image-registry.openshift-image-registry.svc.cluster.local:5000"
  workspaces:
    - name: output
      optional: false
    - name: ssh-directory
      optional: false
  tasks:
    - name: git-clone
      runAfter:
        - create-sa
      taskRef:
        name: git-clone-1-13-0
        kind: ClusterTask
      params:
        - name: url
          value: $(params.url)
      workspaces:
        - name: output
          workspace: output
        - name: ssh-directory
          workspace: ssh-directory
    - name: build-agile-api
      runAfter:
        - git-clone
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: DOCKERFILE
          value: ./environment/agile-api/Dockerfile
        - name: CONTEXT
          value: ./environment/agile-api
        - name: IMAGE
          value: $(params.imageRegistry)/$(context.pipelineRun.namespace)/agile-api:latest
        - name: TLSVERIFY
          value: false
      workspaces:
        - name: source
          workspace: output
    - name: build-resources-api
      taskRef:
        name: buildah
        kind: ClusterTask
      retries: 5
      runAfter:
        - build-agile-api
      params:
        - name: DOCKERFILE
          value: ./environment/resources-api/Dockerfile
        - name: CONTEXT
          value: ./environment/resources-api
        - name: IMAGE
          value: $(params.imageRegistry)/$(context.pipelineRun.namespace)/resources-api:latest
        - name: TLSVERIFY
          value: false
      workspaces:
        - name: source
          workspace: output
    - name: kustomize
      runAfter:
        - build-resources-api
      taskRef:
        name: ibm-pak
      params:
        - name: SCRIPT
          value: |
            #!/bin/bash
            oc apply -k ./environment/
      workspaces:
        - name: manifest-dir
          workspace: output
