configurationset:
  - configuration:
      name: cost-db-config
      uri: STEPZEN_COST_DB_DSN
  - configuration:
      name: sust-db-config
      dsn: STEPZEN_SUST_DB_DSN
  - configuration:
      name: agile-api-config
      url: STEPZEN_AGILE_API_URL
      stepzen.queryextensionguard: "true"
  - configuration:
      name: resources-api-config
      url: STEPZEN_RESOURCES_API_URL
      stepzen.queryextensionguard: "true"
