apiVersion: v1
kind: Service
metadata:
  name: sust-db
spec:
  type: NodePort
  selector:
    app: sust-db
    env: stepzen-playground
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30036