POST http://127.0.0.1:9000/api/bootcamp/__graphql
Content-Type: application/json
Authorization: Apikey #YOUR_API_KEY
X-REQUEST-TYPE: GraphQL

fragment BasicResource on Resource{
  name
  provider
  created
  updated
}
fragment CostV1 on Cost {
  amount
  type
  is_paid
  resource{
  ...BasicResource
  }
}
fragment SustainabilityV1 on Sustainability{
  carbon_dioxide_t
  particulate_matter_amount
  resource{
  ...BasicResource
  }
}
fragment ProjectV1 on Project{
  agile_method
  resource_ids
  team_members_amount
  is_completed
  resource{
  ...BasicResource
  }
}
fragment CapabilityV1 on Capability{
    name
    description
    __typename
}
query ListCaps($resource_id: Int!){
  listCapabilities(resource_id: $resource_id){
    ...CapabilityV1
    ...CostV1
    ...SustainabilityV1
    ...ProjectV1
  }
}

{
  "resource_id": 2
}
